### ISSUE TITLE
Public credentials exposed

### ISSUE THREAD

**Issue by csquared** [sunilnagargojecc/freshactivity#1]
https://github.com/sunilnagargojecc/freshactivity/blob/0725d069cc496df19dd3c31f4038c3065b0fdbf8/routes/activity.js#L82-L83

Hello!
Chris from Bucketeer here. These credentials were available on the public internet, so I've rolled them in your app. Please do not commit them to your code or keep this repo private.
Have a good day!

Cheers,
Chris

**Comment by sunilnagargojecc** [comment]
Thanks, Chris,

I have removed the conditionals from the code.

Thanks
Sunil

**Comment by sunilnagargojecc** [comment]
Can you please it from your comment.
